// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: gallery.proto
package tech.harrynull.galleryneo.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class Image(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val description: String? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val uploaderName: String? = null,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val url: String? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  val timeUploadedMillis: Long? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<Image, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Image) return false
    return unknownFields == other.unknownFields
        && description == other.description
        && uploaderName == other.uploaderName
        && url == other.url
        && timeUploadedMillis == other.timeUploadedMillis
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + description.hashCode()
      result = result * 37 + uploaderName.hashCode()
      result = result * 37 + url.hashCode()
      result = result * 37 + timeUploadedMillis.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (description != null) result += """description=${sanitize(description)}"""
    if (uploaderName != null) result += """uploaderName=${sanitize(uploaderName)}"""
    if (url != null) result += """url=${sanitize(url)}"""
    if (timeUploadedMillis != null) result += """timeUploadedMillis=$timeUploadedMillis"""
    return result.joinToString(prefix = "Image{", separator = ", ", postfix = "}")
  }

  fun copy(
    description: String? = this.description,
    uploaderName: String? = this.uploaderName,
    url: String? = this.url,
    timeUploadedMillis: Long? = this.timeUploadedMillis,
    unknownFields: ByteString = this.unknownFields
  ): Image = Image(description, uploaderName, url, timeUploadedMillis, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<Image> = object : ProtoAdapter<Image>(
      FieldEncoding.LENGTH_DELIMITED, 
      Image::class, 
      "type.googleapis.com/tech.harrynull.galleryneo.proto.Image"
    ) {
      override fun encodedSize(value: Image): Int = 
        ProtoAdapter.STRING.encodedSizeWithTag(1, value.description) +
        ProtoAdapter.STRING.encodedSizeWithTag(2, value.uploaderName) +
        ProtoAdapter.STRING.encodedSizeWithTag(3, value.url) +
        ProtoAdapter.UINT64.encodedSizeWithTag(4, value.timeUploadedMillis) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: Image) {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.description)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.uploaderName)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.url)
        ProtoAdapter.UINT64.encodeWithTag(writer, 4, value.timeUploadedMillis)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): Image {
        var description: String? = null
        var uploaderName: String? = null
        var url: String? = null
        var timeUploadedMillis: Long? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> description = ProtoAdapter.STRING.decode(reader)
            2 -> uploaderName = ProtoAdapter.STRING.decode(reader)
            3 -> url = ProtoAdapter.STRING.decode(reader)
            4 -> timeUploadedMillis = ProtoAdapter.UINT64.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Image(
          description = description,
          uploaderName = uploaderName,
          url = url,
          timeUploadedMillis = timeUploadedMillis,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: Image): Image = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
