// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: gallery.proto
package tech.harrynull.galleryneo.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic
import okio.ByteString

class Image(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val description: String? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val uploaderName: String? = null,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val storeId: String? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  val timeUploadedMillis: Long? = null,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  val id: Long? = null,
  @field:WireField(
    tag = 6,
    adapter = "tech.harrynull.galleryneo.proto.Image${'$'}Permission#ADAPTER"
  )
  val permission: Permission? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<Image, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Image) return false
    return unknownFields == other.unknownFields
        && description == other.description
        && uploaderName == other.uploaderName
        && storeId == other.storeId
        && timeUploadedMillis == other.timeUploadedMillis
        && id == other.id
        && permission == other.permission
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + description.hashCode()
      result = result * 37 + uploaderName.hashCode()
      result = result * 37 + storeId.hashCode()
      result = result * 37 + timeUploadedMillis.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + permission.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (description != null) result += """description=${sanitize(description)}"""
    if (uploaderName != null) result += """uploaderName=${sanitize(uploaderName)}"""
    if (storeId != null) result += """storeId=${sanitize(storeId)}"""
    if (timeUploadedMillis != null) result += """timeUploadedMillis=$timeUploadedMillis"""
    if (id != null) result += """id=$id"""
    if (permission != null) result += """permission=$permission"""
    return result.joinToString(prefix = "Image{", separator = ", ", postfix = "}")
  }

  fun copy(
    description: String? = this.description,
    uploaderName: String? = this.uploaderName,
    storeId: String? = this.storeId,
    timeUploadedMillis: Long? = this.timeUploadedMillis,
    id: Long? = this.id,
    permission: Permission? = this.permission,
    unknownFields: ByteString = this.unknownFields
  ): Image = Image(description, uploaderName, storeId, timeUploadedMillis, id, permission,
      unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<Image> = object : ProtoAdapter<Image>(
      FieldEncoding.LENGTH_DELIMITED, 
      Image::class, 
      "type.googleapis.com/tech.harrynull.galleryneo.proto.Image"
    ) {
      override fun encodedSize(value: Image): Int = 
        ProtoAdapter.STRING.encodedSizeWithTag(1, value.description) +
        ProtoAdapter.STRING.encodedSizeWithTag(2, value.uploaderName) +
        ProtoAdapter.STRING.encodedSizeWithTag(3, value.storeId) +
        ProtoAdapter.UINT64.encodedSizeWithTag(4, value.timeUploadedMillis) +
        ProtoAdapter.UINT64.encodedSizeWithTag(5, value.id) +
        Permission.ADAPTER.encodedSizeWithTag(6, value.permission) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: Image) {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.description)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.uploaderName)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.storeId)
        ProtoAdapter.UINT64.encodeWithTag(writer, 4, value.timeUploadedMillis)
        ProtoAdapter.UINT64.encodeWithTag(writer, 5, value.id)
        Permission.ADAPTER.encodeWithTag(writer, 6, value.permission)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): Image {
        var description: String? = null
        var uploaderName: String? = null
        var storeId: String? = null
        var timeUploadedMillis: Long? = null
        var id: Long? = null
        var permission: Permission? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> description = ProtoAdapter.STRING.decode(reader)
            2 -> uploaderName = ProtoAdapter.STRING.decode(reader)
            3 -> storeId = ProtoAdapter.STRING.decode(reader)
            4 -> timeUploadedMillis = ProtoAdapter.UINT64.decode(reader)
            5 -> id = ProtoAdapter.UINT64.decode(reader)
            6 -> try {
              permission = Permission.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return Image(
          description = description,
          uploaderName = uploaderName,
          storeId = storeId,
          timeUploadedMillis = timeUploadedMillis,
          id = id,
          permission = permission,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: Image): Image = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }
  }

  enum class Permission(
    override val value: Int
  ) : WireEnum {
    PUBLIC(1),

    /**
     * hidden from public gallery and only accessible by the uploader
     */
    PRIVATE(2);

    companion object {
      @JvmField
      val ADAPTER: ProtoAdapter<Permission> = object : EnumAdapter<Permission>(
        Permission::class
      ) {
        override fun fromValue(value: Int): Permission? = Permission.fromValue(value)
      }

      @JvmStatic
      fun fromValue(value: Int): Permission? = when (value) {
        1 -> PUBLIC
        2 -> PRIVATE
        else -> null
      }
    }
  }
}
